MIN_ANGLE_FOR_STRAIGHT_FINGER = 160
MAX_ANGLE_FOR_CRUNCHED_FINGER = 110
MAX_ANGLE_FOR_HORIZONTAL_KNUCKLES = 45

FINGER_OFFSET = {
    'THUMB': 1,
    'INDEX_FINGER': 5,
    'MIDDLE_FINGER': 9,
    'RING_FINGER': 13,
    'PINKY': 17
}
NUMBER_OF_DOTS_PER_FINGER = 4
